
version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true # Keep stdin open even if not attached
    tty: true        # Allocate a pseudo-TTY
